### ISSUE TITLE
[minor] The required packages are not listed

### ISSUE THREAD

**Issue by govarguz** [lanl/GLUE#8]
As the matter of reference, I could not find the required packages for using GLUE within the documentation, nor README. This is essential for the users.

Part of https://github.com/openjournals/joss-reviews/issues/4822

**Comment by rspavel** [comment]
Is there an example of a good practice of formatting this?

On the `GLUECode_Service` side we use a pretty bog standard `requirements.txt` https://github.com/lanl/GLUE/blob/main/GLUECode_Service/requirements.txt

And on the `GLUECode_Library` we list the dependencies both in the https://github.com/lanl/GLUE/blob/main/GLUECode_Library/README.md as well as being part of the CMake build system itself.

**Comment by apachalieva** [comment]
Hi @govarguz, can you give us some directions on how to approach this issue?

**Comment by govarguz** [comment]
Hi @apachalieva, sure! this is a pretty clear case https://github.com/espressopp/espressopp you could use for the GLUECode_Library and also in general, as an example.
